### ISSUE TITLE
Endianness conversion

### ISSUE THREAD

**Issue by adamnemecek** [RoaringBitmap/RoaringFormatSpec#11]
Hello,
RoaringBitmap is really nice. I think that the one thing that it might be missing is dealing with endianness esp when it comes to serialization. I think that as a part of the cookie headers, there should be a bit indicating whether the bitmap is little or big endian and then there should be method to check the endianness and also to convert it to and from little/big endian. I think that this functionality makes more sense in the library than outside of it. 

Let me know what you think.

**Comment by adamnemecek** [comment]
I might not need this.

**Comment by lemire** [comment]
It must be little endian. It is part of the specification.
