### ISSUE TITLE
Refer to Delta's specification

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringFormatSpec#13]
@larsk-db pointed out that they have 64-bit serialisation format in Delta: https://docs.google.com/document/d/1lv35ZPfioopBbzQ7zT82LOev7qV7x4YNLkMr2-L5E_M/edit#heading=h.yvlcj9hgj4tr

Possibly, our documents should reference it.

**Comment by larsk-db** [comment]
I'm actually pushing right now for us to change to the portable one we agreed upon today. I think it will benefit Delta as an open source ecosystem to use a "standard"/"portable" format, rather than rolling our own, especially with respect to 3rd-party connector effort and compatibility.

**Comment by lemire** [comment]
Closing then.
