### ISSUE TITLE
Lack of clarity around what type a container with cardinality exactly 4096

### ISSUE THREAD

**Issue by Dr-Emann** [RoaringBitmap/RoaringFormatSpec#14]
> then we use the cardinality to determine the type: a cardinality of up to 4096 indicates an array container whereas a cardinality above 4096 indicates a bitset container.

I think changing "up to" to "up to and including" would clarify what should happen with a cardinality of exactly 4096.

https://oneminuteenglish.org/en/up-to-inclusive-or-exclusive/ says

> “Up to” can have an exclusive meaning when dealing with subjects that are more precise like maths and software development.
> The best way to avoid confusion is to use “up to and including X” or “up to and not including X ”, where X is the upper limit.

**Comment by lemire** [comment]
Pull request invited.
