### ISSUE TITLE
“The cookie header spans either 32 bits or 64 bits.” What does this sentence mean? 

### ISSUE THREAD

**Issue by gskeno** [RoaringBitmap/RoaringFormatSpec#16]
In  Cookie header chapter， the first sentence is "The cookie header spans either 32 bits or 64 bits".

but in fact,  cookie header in  roaringBitmap use 8 bytes( 32bits) when has no runContainer,    or either use `( 4 + (size + 7) / 8)` bytes( uncertain bits) when has runContainer.      so  what's the meaning of the `either 32 bits or 64 bits` ? i'm a little confused，hope to get some explains.

may be, i got it.  32bits means the  `SERIAL_COOKIE | ((size - 1) << 16`, it does not include runFlagBitset, it's not describes accurately in my view

**Comment by lemire** [comment]
Yes. Corrected to:

> The cookie header spans either 64 bits or 32 bits followed by a variable number of bytes
