### ISSUE TITLE
Wrong cookie header description in diagram.png.

### ISSUE THREAD

**Issue by AAAbramenko** [RoaringBitmap/RoaringFormatSpec#5]
In [diagram.png](https://github.com/RoaringBitmap/RoaringFormatSpec/blob/master/diagram.png) we see **4** bytes for (Cookie) and **4** bytes for (Nc = Container count). 
But in according to RoaringFormatSpec in case of bitmap has run containers description should be:
- **2** bytes for (Cookie = SERIAL_COOKIE);
- **2** bytes for (Nc = Container count **- 1**).
This discrepancy makes confused.

**Comment by lemire** [comment]
That's correct, the diagram is misleading. I have updated it in git, but it should take some time before you can see the updated diagram due to image caching.

Re-open if an error is still present after a few hours.
