### ISSUE TITLE
Three questions about RoaringFormatSpec.

### ISSUE THREAD

**Issue by skyduy** [RoaringBitmap/RoaringFormatSpec#8]
I hava three questions about the RoaringFormatSpec:

- Question1: What does "The cookie header spans either 32 bits or 64 bits." mean?

    If the cookie takes the value SERIAL_COOKIE_NO_RUNCONTAINER, it will consume 64bits totally, and I understand it as the cookie header spans 64bits.

    But if the cookie takes the value SERIAL_COOKIE, as shown in the picture below, it will take 32bit to store SERIAL_COOKIE and Container count, but another `(size + 7) / 8` bytes to store RUN infomation. 
![image](https://user-images.githubusercontent.com/7315313/74585387-06656680-5017-11ea-9edf-e37570ecd37f.png)

    Then, what does "The cookie header spans either 32 bits or 64 bits." mean?

- Question2: Why runFlagBitset take `(size + 7) / 8` bytes, not `size/8`?

- Question3: When will we use NO_OFFSET_THRESHOLD in Cookie Header?

Waiting for your reply, Thank you.

**Comment by lemire** [comment]
Q1. I do not understand your question. It seems that you have understood that the cookie is either 32 bits or 64 bits by your description.

**Comment by lemire** [comment]
Q2. The result of the division is an integer. If size = 7, then size/8 = 7/8 = 0. Keep in mind that we use integer division. With 0 bytes, you cannot represent 7 bits.

**Comment by lemire** [comment]
Q3. Please see section "3. Offset header" in the specification.

**Comment by skyduy** [comment]
Thank you very much, I have understood all of them.
